---
  - name: Whats in the list
    debug:
      msg: "printing {{ item.key }}"
    with_dict: "{{ infrastructure }}"


  - name: 'Create server stack servers'
    os_server:
      cloud: ospcloud
      name: "{{ item.key }}"
      flavor: "{{ item.value.flavor }}"
      image: rhel-guest
      security_groups:
      - "{{ item.value.security_groups }}"
      wait: yes
      meta: "group={{ item.value.metadata.group }},deployment_name={{ item.value.metadata.deployment_name }}"
      nics:
      - net-name: int_network
      userdata: |
        #!/bin/bash
        curl -o /tmp/openstack.pub http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pub
        cat /tmp/openstack.pub >> /home/cloud-user/.ssh/authorized_keys
        chmod 0600 /home/cloud-user/.ssh/authorized_keys
        curl -o /tmp/internal.repo http://www.opentlc.com/download/ansible_bootcamp/repo/internal.repo
        cp /tmp/internal.repo /etc/yum.repos.d/internal.repo
    register: instanceip
    with_dict: "{{ infrastructure }}"


  - name: "Add floating IP to"
    os_floating_ip:
      cloud: ospcloud
      state: present
      reuse: yes
      server: "{{ item.key }}"
      network: ext_network
      wait: true
      timeout: 180
    register: instancefloatingip
    with_dict: "{{ infrastructure }}"
  - name: test
    debug: var=instancefloatingip
  - name: "Show {{ item.key }} public IP"
    debug:
      var: instancefloatingip.results[0].floating_ip.floating_ip_address
    with_dict: "{{ infrastructure }}"
  - name: "Wait for {{ item.key }} to be available"
    wait_for:
      host: "{{ instancefloatingip.results[0].floating_ip.floating_ip_address }}"
      port: 22
      search_regex: OpenSSH
      timeout: 600
    delegate_to: "{{ inventory_hostname }}"
    with_dict: "{{ infrastructure }}"