- hosts: jumpbox
  tasks:
  - name: Remove an old one first
    os_nova_flavor:
     cloud: ospcloud
     state: absent
     name: m2.small
  - name: Create m2.small flavor
    os_nova_flavor:
     cloud: ospcloud
     state: present
     name: m2.small
     ram: 2048
     vcpus: 1
     disk: 10
