---
  security_groups:
    app_security:
      - { port: '8080', ip_prefix: '0.0.0.0/0' }
      - { port: '22', ip_prefix: '0.0.0.0/0' }
    frontend_servers:
      - { port: '80', ip_prefix: '0.0.0.0/0' }
      - { port: '443', ip_prefix: '0.0.0.0/0' }
      - { port: '22', ip_prefix: '0.0.0.0/0' }
    db_servers:
      - { port: '5432', ip_prefix: '20.20.20.0/24' }
      - { port: '22', ip_prefix: '0.0.0.0/0' }